[project]
name = "industrial-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncua>=1.0.0",
    "mcp>=1.13.1",
]
